"""Flow-analysis public API covering customer-facing post-processing workflows."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES = {
    "BaseFlowAnalyzer": "naviertwin.core.flow_analysis.base",
    "mean_field": "naviertwin.core.flow_analysis.reynolds_stats",
    "fluctuation": "naviertwin.core.flow_analysis.reynolds_stats",
    "rms": "naviertwin.core.flow_analysis.reynolds_stats",
    "reynolds_stress_2d": "naviertwin.core.flow_analysis.reynolds_stats",
    "reynolds_stress_3d": "naviertwin.core.flow_analysis.reynolds_stats",
    "turbulent_kinetic_energy": "naviertwin.core.flow_analysis.reynolds_stats",
    "turbulence_intensity": "naviertwin.core.flow_analysis.reynolds_stats",
    "skewness": "naviertwin.core.flow_analysis.reynolds_stats",
    "flatness": "naviertwin.core.flow_analysis.reynolds_stats",
    "running_statistics": "naviertwin.core.flow_analysis.reynolds_stats",
    "welch_psd": "naviertwin.core.flow_analysis.psd",
    "cross_psd": "naviertwin.core.flow_analysis.psd",
    "coherence": "naviertwin.core.flow_analysis.psd",
    "triangle_normal_area": "naviertwin.core.flow_analysis.surface_integrals",
    "pressure_force": "naviertwin.core.flow_analysis.surface_integrals",
    "viscous_force": "naviertwin.core.flow_analysis.surface_integrals",
    "total_force": "naviertwin.core.flow_analysis.surface_integrals",
    "moment_about": "naviertwin.core.flow_analysis.surface_integrals",
    "force_coefficient": "naviertwin.core.flow_analysis.surface_integrals",
    "moment_coefficient": "naviertwin.core.flow_analysis.surface_integrals",
    "lift_drag_split": "naviertwin.core.flow_analysis.surface_integrals",
    "quadrant_split": "naviertwin.core.flow_analysis.quadrant_pdf",
    "histogram_pdf": "naviertwin.core.flow_analysis.quadrant_pdf",
    "kde_pdf": "naviertwin.core.flow_analysis.quadrant_pdf",
    "joint_pdf_2d": "naviertwin.core.flow_analysis.quadrant_pdf",
    "spatial_autocorrelation": "naviertwin.core.flow_analysis.two_point",
    "temporal_autocorrelation": "naviertwin.core.flow_analysis.two_point",
    "integral_length_scale_from_R": "naviertwin.core.flow_analysis.two_point",
    "integral_time_scale_from_R": "naviertwin.core.flow_analysis.two_point",
    "taylor_microscale": "naviertwin.core.flow_analysis.two_point",
    "batch_means_se": "naviertwin.core.flow_analysis.stat_convergence",
    "geweke_diagnostic": "naviertwin.core.flow_analysis.stat_convergence",
    "effective_sample_size": "naviertwin.core.flow_analysis.stat_convergence",
    "plateau_detector": "naviertwin.core.flow_analysis.stat_convergence",
    "autocorrelation_time": "naviertwin.core.flow_analysis.stat_convergence",
    "mass_flux": "naviertwin.core.flow_analysis.plane_flux",
    "volumetric_flow_rate": "naviertwin.core.flow_analysis.plane_flux",
    "momentum_flux": "naviertwin.core.flow_analysis.plane_flux",
    "scalar_flux": "naviertwin.core.flow_analysis.plane_flux",
    "kinetic_energy_flux": "naviertwin.core.flow_analysis.plane_flux",
    "area_average": "naviertwin.core.flow_analysis.plane_flux",
    "mass_weighted_average": "naviertwin.core.flow_analysis.plane_flux",
    "interp_field": "naviertwin.core.flow_analysis.time_interp",
    "resample_uniform": "naviertwin.core.flow_analysis.time_interp",
    "time_average_window": "naviertwin.core.flow_analysis.time_interp",
    "cart_to_cyl": "naviertwin.core.flow_analysis.coord_transform",
    "cyl_to_cart": "naviertwin.core.flow_analysis.coord_transform",
    "cart_to_sph": "naviertwin.core.flow_analysis.coord_transform",
    "sph_to_cart": "naviertwin.core.flow_analysis.coord_transform",
    "vector_cart_to_cyl": "naviertwin.core.flow_analysis.coord_transform",
    "vector_cyl_to_cart": "naviertwin.core.flow_analysis.coord_transform",
    "axis_align_rotation": "naviertwin.core.flow_analysis.coord_transform",
    "slice_axis_aligned": "naviertwin.core.flow_analysis.slice_extract",
    "slice_plane_arbitrary": "naviertwin.core.flow_analysis.slice_extract",
    "line_probe": "naviertwin.core.flow_analysis.slice_extract",
    "polyline_arc_length": "naviertwin.core.flow_analysis.slice_extract",
    "ExpressionError": "naviertwin.core.flow_analysis.expression_eval",
    "safe_eval": "naviertwin.core.flow_analysis.expression_eval",
    "list_supported_functions": "naviertwin.core.flow_analysis.expression_eval",
    "list_supported_constants": "naviertwin.core.flow_analysis.expression_eval",
    "phase_average": "naviertwin.core.flow_analysis.phase_lock",
    "cycle_extract": "naviertwin.core.flow_analysis.phase_lock",
    "fundamental_period_from_acf": "naviertwin.core.flow_analysis.phase_lock",
    "RunningMoments": "naviertwin.core.flow_analysis.running_moments",
    "RunningCovariance": "naviertwin.core.flow_analysis.running_moments",
    "online_mean_var": "naviertwin.core.flow_analysis.running_moments",
    "savgol_filter": "naviertwin.core.flow_analysis.denoise",
    "moving_average": "naviertwin.core.flow_analysis.denoise",
    "moving_median": "naviertwin.core.flow_analysis.denoise",
    "hampel_filter": "naviertwin.core.flow_analysis.denoise",
    "soft_threshold": "naviertwin.core.flow_analysis.denoise",
    "hard_threshold": "naviertwin.core.flow_analysis.denoise",
    "universal_threshold": "naviertwin.core.flow_analysis.denoise",
    "estimate_noise_sigma_mad": "naviertwin.core.flow_analysis.denoise",
    "percentile": "naviertwin.core.flow_analysis.quantile_stats",
    "quartiles": "naviertwin.core.flow_analysis.quantile_stats",
    "iqr": "naviertwin.core.flow_analysis.quantile_stats",
    "box_stats": "naviertwin.core.flow_analysis.quantile_stats",
    "empirical_cdf": "naviertwin.core.flow_analysis.quantile_stats",
    "outliers_iqr": "naviertwin.core.flow_analysis.quantile_stats",
    "trimmed_mean": "naviertwin.core.flow_analysis.quantile_stats",
    "winsorized_mean": "naviertwin.core.flow_analysis.quantile_stats",
    "eof_decomposition": "naviertwin.core.flow_analysis.eof_analysis",
    "reconstruct_from_eof": "naviertwin.core.flow_analysis.eof_analysis",
    "north_significance_test": "naviertwin.core.flow_analysis.eof_analysis",
    "varimax_rotation": "naviertwin.core.flow_analysis.eof_analysis",
    "ks_test_against_cdf": "naviertwin.core.flow_analysis.goodness_of_fit",
    "ks_test_normal": "naviertwin.core.flow_analysis.goodness_of_fit",
    "ks_test_two_sample": "naviertwin.core.flow_analysis.goodness_of_fit",
    "anderson_darling_normal": "naviertwin.core.flow_analysis.goodness_of_fit",
    "chi_square_test": "naviertwin.core.flow_analysis.goodness_of_fit",
    "shapiro_wilk_simplified": "naviertwin.core.flow_analysis.goodness_of_fit",
    "normal_cdf": "naviertwin.core.flow_analysis.goodness_of_fit",
    "find_threshold_crossings": "naviertwin.core.flow_analysis.conditional_sampling",
    "trigger_average": "naviertwin.core.flow_analysis.conditional_sampling",
    "conditional_average": "naviertwin.core.flow_analysis.conditional_sampling",
    "quadrant_masks": "naviertwin.core.flow_analysis.conditional_sampling",
    "event_duration_stats": "naviertwin.core.flow_analysis.conditional_sampling",
    "gradient_2d": "naviertwin.core.flow_analysis.grid_derivatives",
    "gradient_3d": "naviertwin.core.flow_analysis.grid_derivatives",
    "divergence_3d": "naviertwin.core.flow_analysis.grid_derivatives",
    "curl_3d": "naviertwin.core.flow_analysis.grid_derivatives",
    "laplacian_2d": "naviertwin.core.flow_analysis.grid_derivatives",
    "laplacian_3d": "naviertwin.core.flow_analysis.grid_derivatives",
    "classify_2d": "naviertwin.core.flow_analysis.critical_points",
    "find_critical_points": "naviertwin.core.flow_analysis.critical_points",
    "poincare_index": "naviertwin.core.flow_analysis.critical_points",
    "anisotropy_tensor": "naviertwin.core.flow_analysis.anisotropy",
    "invariants_II_III": "naviertwin.core.flow_analysis.anisotropy",
    "lumley_eta_xi": "naviertwin.core.flow_analysis.anisotropy",
    "is_realizable": "naviertwin.core.flow_analysis.anisotropy",
    "turbulence_state": "naviertwin.core.flow_analysis.anisotropy",
    "reynolds_stress_eigenvalues": "naviertwin.core.flow_analysis.anisotropy",
    "barycentric_coordinates": "naviertwin.core.flow_analysis.anisotropy",
    "binary_dilation_2d": "naviertwin.core.flow_analysis.morphology",
    "binary_erosion_2d": "naviertwin.core.flow_analysis.morphology",
    "binary_opening_2d": "naviertwin.core.flow_analysis.morphology",
    "binary_closing_2d": "naviertwin.core.flow_analysis.morphology",
    "connected_components_2d": "naviertwin.core.flow_analysis.morphology",
    "component_sizes": "naviertwin.core.flow_analysis.morphology",
    "remove_small_components": "naviertwin.core.flow_analysis.morphology",
    "threshold_to_mask": "naviertwin.core.flow_analysis.morphology",
    "tet_volume": "naviertwin.core.flow_analysis.cell_volume",
    "tet_volumes_batch": "naviertwin.core.flow_analysis.cell_volume",
    "hex_volume": "naviertwin.core.flow_analysis.cell_volume",
    "pyramid_volume": "naviertwin.core.flow_analysis.cell_volume",
    "prism_volume": "naviertwin.core.flow_analysis.cell_volume",
    "volume_integral": "naviertwin.core.flow_analysis.cell_volume",
    "volume_average": "naviertwin.core.flow_analysis.cell_volume",
    "volume_weighted_variance": "naviertwin.core.flow_analysis.cell_volume",
    "cell_centroids": "naviertwin.core.flow_analysis.cell_volume",
}

__all__ = list(_EXPORT_MODULES)


def __getattr__(name: str) -> Any:
    """Lazily expose flow-analysis helpers without importing optional backends."""
    if name not in _EXPORT_MODULES:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(_EXPORT_MODULES[name])
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    """Return stable public members used by autocomplete and Sphinx."""
    return sorted([*globals(), *__all__])
