"""Jinja2 기반 NavierTwin 실행 보고서 생성.

실행 결과 dict (모델, 메트릭, 그림 경로) → HTML / PDF 생성.
weasyprint 미설치 시 HTML 만 반환.

Examples:
    >>> import tempfile, os
    >>> from naviertwin.core.report.generator import ReportGenerator
    >>> data = {
    ...     "project": "Cavity Flow Digital Twin",
    ...     "summary": "POD 5 modes + Kriging surrogate",
    ...     "metrics": {"rmse": 0.0123, "r2": 0.995},
    ...     "figures": [],
    ... }
    >>> with tempfile.TemporaryDirectory() as d:
    ...     out = ReportGenerator().render_html(data, os.path.join(d, "r.html"))
    ...     os.path.exists(out)
    True
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

from naviertwin.utils.logger import get_logger

logger = get_logger(__name__)


_DEFAULT_TEMPLATE = """<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="utf-8">
<title>{{ project }} — NavierTwin Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 2em auto; color: #222; }
  h1 { border-bottom: 2px solid #335; padding-bottom: 0.2em; }
  h2 { color: #335; margin-top: 1.5em; }
  table { border-collapse: collapse; margin: 1em 0; }
  th, td { padding: 0.4em 0.9em; border-bottom: 1px solid #ddd; text-align: left; }
  .summary { background: #f5f7fa; padding: 1em 1.5em; border-left: 4px solid #335; }
  .figure { margin: 1em 0; }
  .meta { color: #888; font-size: 0.85em; }
</style>
</head>
<body>
<h1>{{ project }}</h1>
<p class="meta">Generated by NavierTwin on {{ timestamp }}</p>

<h2>Summary</h2>
<div class="summary">{{ summary }}</div>

{% if metrics %}
<h2>Validation Metrics</h2>
<table>
  <tr><th>Metric</th><th>Value</th></tr>
  {% for k, v in metrics.items() %}
  <tr><td>{{ k }}</td><td>{{ "%.6g"|format(v) }}</td></tr>
  {% endfor %}
</table>
{% endif %}

{% if model_info %}
<h2>Model Information</h2>
<table>
  {% for k, v in model_info.items() %}
  <tr><td>{{ k }}</td><td>{{ v }}</td></tr>
  {% endfor %}
</table>
{% endif %}

{% if figures %}
<h2>Figures</h2>
{% for fig in figures %}
<div class="figure">
  <img src="{{ fig.path }}" alt="{{ fig.caption }}" style="max-width:100%;">
  <p><em>{{ fig.caption }}</em></p>
</div>
{% endfor %}
{% endif %}

{% if notes %}
<h2>Notes</h2>
<p>{{ notes }}</p>
{% endif %}
</body>
</html>
"""


class ReportGenerator:
    """Jinja2 템플릿 기반 보고서 생성기."""

    def __init__(self, template: str | None = None) -> None:
        self.template_str = template or _DEFAULT_TEMPLATE

    def _render(self, data: dict[str, Any]) -> str:
        try:
            from jinja2 import Environment
        except ImportError as exc:
            raise RuntimeError(
                "jinja2 설치 필요: pip install jinja2"
            ) from exc

        from datetime import datetime

        env = Environment(autoescape=True)
        tmpl = env.from_string(self.template_str)
        ctx = {
            "project": data.get("project", "Untitled"),
            "summary": data.get("summary", ""),
            "metrics": data.get("metrics", {}),
            "model_info": data.get("model_info", {}),
            "figures": data.get("figures", []),
            "notes": data.get("notes", ""),
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M"),
        }
        return tmpl.render(**ctx)

    def render_html(
        self, data: dict[str, Any], out_path: str | Path
    ) -> Path:
        """데이터 → HTML 파일 저장."""
        html = self._render(data)
        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(html, encoding="utf-8")
        logger.info("HTML 보고서 저장: %s", out)
        return out

    def render_pdf(
        self, data: dict[str, Any], out_path: str | Path
    ) -> Path:
        """데이터 → PDF (weasyprint 필요).

        Raises:
            RuntimeError: weasyprint 미설치 시.
        """
        try:
            from weasyprint import HTML
        except ImportError as exc:
            raise RuntimeError(
                "weasyprint 설치 필요: pip install weasyprint"
            ) from exc

        html = self._render(data)
        out = Path(out_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        HTML(string=html).write_pdf(str(out))
        logger.info("PDF 보고서 저장: %s", out)
        return out


__all__ = ["ReportGenerator"]
